###
GET http://localhost:8080/api/vacas HTTP/1.1

###
GET http://localhost:8080/api/vacas/1 HTTP/1.1



###
POST http://localhost:8080/api/vacas/create HTTP/1.1
Content-Type: application/json

{
    "Raza": "angusss",
    "Edad": 40,
    "peso": 3,
}

